#Write a programme that displays a diamond pattern
print("* * * * * * * * * * * * * * * *  *                                    ")
print("  * * * * * * * * * * * * * * *                                      ")
print("    * * * * * * * * * * * *                                   ")
print("      * * * * * * * * * *                                ")
print("        * * * * * * * *                            ")
print("          * * * * * *                        ")
print("            * * * *                    ")
print("              * *                      ")
print("               *                ")
